-- =====================================================================
-- Migrations pendentes — Auditoria 22 agentes, 20/08/2026
-- NÃO APLICADO. Arquivo só documenta SQL para o usuário revisar/aplicar
-- manualmente (ou autorizar aplicação em sessão futura). Nenhum destes
-- comandos foi rodado contra o Supabase por este agente.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Achado: domínio Arquitetura / item "V2 Relacional" — wallace_dados (V1)
-- sem proteção explícita contra escrita acidental futura.
-- ---------------------------------------------------------------------
--
-- INVESTIGAÇÃO (20/08/2026):
--
-- 1. Código do repositório (grep em src/**): nenhuma ocorrência de
--    `.from('wallace_dados')` nem de `.insert(`/`.update(`/`.upsert(`/
--    `.delete(` associada a wallace_dados em lugar nenhum de src/**.
--    Todas as ~60 menções ao nome da tabela são comentários históricos
--    documentando a migração para V2 (ver app.js, vars-mercado-pago.js,
--    etc.). Confirma: wallace_dados está morta no código do painel.
--
-- 2. Banco (Supabase, projeto bakdgacmwlopvrrppwdm), estado real hoje:
--
--    a) GRANTs de tabela (information_schema.role_table_grants):
--       - anon:            SELECT apenas
--       - authenticated:   SELECT apenas
--       - postgres:        INSERT/UPDATE/DELETE/SELECT/REFERENCES/TRIGGER/TRUNCATE
--       - service_role:    INSERT/UPDATE/DELETE/SELECT/REFERENCES/TRIGGER/TRUNCATE
--       => anon/authenticated NUNCA tiveram INSERT/UPDATE/DELETE
--          concedido nesta tabela. Não há nada a revogar nesse nível.
--
--    b) RLS: relrowsecurity = true (RLS ligada). 4 políticas ativas,
--       todas com qual/with_check exigindo
--       `(select auth.role()) = 'service_role'::text`:
--         - "Leitura via service role"        (SELECT)
--         - "Escrita via service role (insert)" (INSERT)
--         - "Escrita via service role (update)" (UPDATE)
--         - "Escrita via service role (delete)" (DELETE)
--       Não existe nenhuma policy permissiva para anon/authenticated
--       em nenhuma operação. Ou seja: mesmo o SELECT que o GRANT de
--       tabela permite a anon/authenticated é bloqueado na prática
--       pela RLS, porque nenhuma policy libera esses papéis.
--
--    c) Não há trigger nenhum na tabela wallace_dados (pg_trigger,
--       excluindo triggers internos): resultado vazio.
--
--    d) Não há função/RPC no schema public cujo corpo (pg_get_functiondef)
--       mencione wallace_dados: resultado vazio.
--
-- CONCLUSÃO: o achado da auditoria ("sem nenhuma proteção contra escrita
-- acidental") NÃO procede no estado atual do banco — a tabela já está
-- protegida em duas camadas independentes (GRANT nunca deu write a
-- anon/authenticated, e a RLS já restringe todas as 4 operações a
-- service_role). Nenhum agente que use a chave anon/authenticated
-- (o caminho normal do painel via PostgREST) consegue gravar nela hoje,
-- mesmo sem ler o manual. Não force uma correção artificial aqui —
-- o "erro real de permissão" pedido pela tarefa já existe de fato via RLS.
--
-- HARDENING OPCIONAL (defesa em profundidade, não obrigatório):
-- o GRANT de SELECT a anon/authenticated é hoje inofensivo (a RLS barra
-- a leitura de qualquer forma), mas é redundante e depende de ninguém
-- desligar a RLS por engano no futuro (ALTER TABLE ... DISABLE ROW LEVEL
-- SECURITY). Revogar o SELECT residual remove essa dependência silenciosa
-- e deixa a intenção explícita em duas camadas em vez de uma. Fica a
-- critério do usuário aplicar ou não — não é correção de um problema
-- real, é reforço de um controle que já funciona.
--
-- Se o usuário optar por aplicar o hardening opcional:

-- REVOKE SELECT ON TABLE public.wallace_dados FROM anon, authenticated;

-- (INSERT/UPDATE/DELETE de anon/authenticated: já não existem, nada a revogar)
-- (service_role e postgres: mantidos como estão — service_role precisa
--  continuar podendo ler/escrever caso algum processo administrativo
--  ainda dependa dela; postgres é o owner)

-- Verificação pós-aplicação (se decidir aplicar):
-- SELECT grantee, privilege_type FROM information_schema.role_table_grants
-- WHERE table_schema = 'public' AND table_name = 'wallace_dados'
-- ORDER BY grantee, privilege_type;

-- APLICADA 20/08/2026 (autorizado pelo usuário) — confirmada via pg_constraint,
-- medidor_tuya_consumo_diario_pkey existe. Bloco abaixo mantido como histórico.
-- =====================================================================
-- Achado: domínio Segurança/Supabase — medidor_tuya_consumo_diario sem PK
-- (regenerado 20/08/2026 — perdido por race condition entre 3 agentes
-- escrevendo neste mesmo arquivo em paralelo na 1ª rodada; investigação
-- original preservada, só reescrevendo o SQL)
-- =====================================================================
--
-- Confirmado via pg_constraint: a tabela já tem
-- `medidor_tuya_consumo_diario_data_casa_key UNIQUE (data, casa)`, e o
-- trigger que a alimenta já faz INSERT ... ON CONFLICT (data, casa) — ou
-- seja, o código já trata (data, casa) como identidade da linha. Não faz
-- sentido criar uma coluna `id` surrogate sem uso; a correção é só
-- promover a UNIQUE existente a PRIMARY KEY.

-- ALTER TABLE public.medidor_tuya_consumo_diario
--   DROP CONSTRAINT medidor_tuya_consumo_diario_data_casa_key,
--   ADD PRIMARY KEY (data, casa);

-- APLICADA 20/08/2026 (autorizado pelo usuário) — origem_ip existe, função
-- reescrita e confirmada. Bloco abaixo mantido como histórico.
-- =====================================================================
-- Achado: domínio Segurança — registrar_erro_cliente sem rate limit
-- (regenerado 20/08/2026, mesmo motivo do bloco acima)
-- =====================================================================
--
-- RPC SECURITY DEFINER, EXECUTE liberado pra anon (precisa registrar erro
-- antes do login) — confirmado via pg_get_functiondef, hoje aceita
-- qualquer volume de INSERT sem limite algum. Tabela erros_cliente hoje
-- só tem: id, ocorrido_em, mensagem, stack, contexto (sem coluna de
-- origem/IP). Adiciona origem_ip (capturado no SERVIDOR via
-- current_setting('request.headers', true), nunca confiando em valor
-- vindo do corpo da chamada) e um teto de 20 registros/5min por origem,
-- descartando silenciosamente acima disso (best-effort, mesmo critério já
-- usado no resto da observabilidade — não lança exceção pro cliente).

-- ALTER TABLE public.erros_cliente ADD COLUMN IF NOT EXISTS origem_ip text;
--
-- CREATE OR REPLACE FUNCTION public.registrar_erro_cliente(
--   p_mensagem text, p_stack text DEFAULT NULL, p_contexto jsonb DEFAULT NULL
-- )
-- RETURNS void
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- SET search_path TO 'public'
-- AS $function$
-- declare
--   v_ip text;
--   v_recentes int;
-- begin
--   v_ip := coalesce(
--     (current_setting('request.headers', true)::json ->> 'x-forwarded-for'),
--     'desconhecido'
--   );
--   select count(*) into v_recentes
--   from public.erros_cliente
--   where origem_ip = v_ip and ocorrido_em > now() - interval '5 minutes';
--   if v_recentes >= 20 then
--     return; -- descarta silenciosamente, sem exceção pro cliente
--   end if;
--   insert into public.erros_cliente (mensagem, stack, contexto, origem_ip)
--   values (left(p_mensagem, 2000), left(coalesce(p_stack, ''), 4000), p_contexto, v_ip);
-- end;
-- $function$;

-- Verificação pós-aplicação (se decidir aplicar):
-- SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint
-- WHERE conrelid = 'medidor_tuya_consumo_diario'::regclass;
-- SELECT pg_get_functiondef(oid) FROM pg_proc WHERE proname = 'registrar_erro_cliente';
